# [Info]
site_name: Pengyu-Jin's personal website # 左上角标题
site_url: https://jin-pengyu.github.io/
site_author: 靳鹏宇
site_description: 靳鹏宇的个人网站

#[Navigation]
nav:
  - Major:
      - major/index.md
      - Research: major/research/research.md
      - EE:
          - Power Electronics: major/EE/PE.md
          - Power System: major/EE/Power System.md
          - Electric Motor: major/EE/electric-motor.md
      - Flybook:
          - Fly: major/flybook/fly.md
          - Culture: major/flybook/culture.md
      - AI: major/AI/Agent.md
      - EN Learn:
          - major/EN-learn/index.md
          - Larry grammar course: major/EN-learn/Larry.md
          - Phrase: major/EN-learn/phrase.md
          - Phonetic symbol: major/EN-learn/phonetic symbol.md
          - Why: major/EN-learn/why.md
      - Mathmatic: major/math/math.md
      

  - Interest:
      - interest/index.md
      - programming:
          - Python: interest/programming/Python.md
          - C: interest/programming/C.md
          - LeetCode: interest/programming/leetcode.md
          - CheatSheet: interest/programming/cheatsheet.md
      - finance: interest/finance/learn1.md
      - career: interest/career/career.md
      - digital technology:
          - Hardware: interest/digital technology/hardware.md
          - Network: interest/digital technology/net.md
          - Image: interest/digital technology/image.md
          - PT: interest/digital technology/pt.md
      - Insights on life: interest/LifeRoad/liferoad.md
      - Vehicle: interest/Vehicle/Vehicle_infor.md
      - game: interest/game/pokemon.md
      - markdown grammar: interest/markdown/markdown.md
      - 党建: interest/party building/info.md

  - Blog:
      - blog/index.md

  - About:
      - about/index.md
      - bio:
          - CV: about/personal profile/cv.md 


#[UI]

## [top]

theme:
  # font:
  #   text: Poppins

  # font-family: Satoshi-Variable, Noto Sans SC, -apple-system, system-ui, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif, BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB, Microsoft YaHei, Arial;
  # font-weight: 450;
  # font-size: 16px;

  name: material
  logo: logo.ico
  favicon: logo.ico
  palette:
    - scheme: default # 日间模式
      primary: white # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    #- navigation.tabs.sticky # 粘性导航标签，sticky navigation tab
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy #copy code 按钮
    - content.code.annotate # 代码注解
  language: zh # 一些提示性的文字会变成中文

  
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]

repo_url: https://github.com/Jin-Pengyu/jin-pengyu.github.io # 右上角点击跳转的链接
repo_name: Pengyu-Jin.github.io # 右上角的名字

## [bottom-left corner]

copyright: Pengyu Jin CC-BY-4.0 # 左下角的版权声明

## [bottom-right corner]

extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/435864762
      name: Bilibili | 鸽子和野狗 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Jin-Pengyu
      name: GitHub | Jin-Pengyu
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/zhi-nian-20-34-4
      name: zhihu | 希斯特利亚

## [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

  - blog: #blog 插件
      blog_toc: true ##显示 Blog中每篇博客的标题 构成的目录
      archive: true
      categories: true





markdown_extensions:
  - footnotes #添加注脚footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde #实现markdown中的文字高亮效果
  - pymdownx.arithmatex:
      generic: true # latex支持
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - meta # 支持Markdown文件上方自定义标题标签等

  
  - def_list #List列表相关
  - pymdownx.tasklist:
      custom_checkbox: true  

  - admonition   #添加admonition  https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details  # admonition需要
  - pymdownx.superfences
 
  - pymdownx.tabbed:  #添加content tab功能
      alternate_style: true

  # annotation 注解
  - md_in_html

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # 代码块语法高亮
  - pymdownx.highlight:
      linenums: true 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# 在此处添加 lang 设置
extra:
  lang: "zh"  # 或者 "en"，根据需要

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
#   - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
  - mkdocs/css/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css    # 从https://github.com/LLMQuant/quant-wiki/tree/master拿来的



extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0


