# [Info]
site_name: 靳鹏宇的个人网站 # 左上角标题
site_url: https://jin-pengyu.github.io/my-website/
site_author: 靳鹏宇
site_description: 靳鹏宇的个人网站

#[Navigation]
nav:
  - 专业:
      - major/index.md
      - 电力系统:
          - 专业英语: major/Power System Analysis/pre.md
          - 第一章：课程绪论: major/Power System Analysis/chapter1.md
          - 第二章: major/Power System Analysis/chapter2.md
      - 电力科普:
          - 第三届北大能源论坛: major/popularization/1.md
  - 博客:
      - blog/index.md
      - 影视: blog/vedio/blu-ray.md
      - 信息: blog/information/infor.md
  - 关于:
      - about/index.md
      - 个人履历: about/personal profile/p p.md
#[UI]

## [top]

theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.tabs.sticky # 粘性导航标签
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]

repo_url: https://jin-pengyu.github.io/my-website/ # 右上角点击跳转的链接
repo_name: jin-pengyu.github.io # 右上角的名字

## [bottom-left corner]

copyright: 靳鹏宇 CC-BY-4.0 # 左下角的版权声明

## [bottom-right corner]

extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/435864762
      name: Bilibili | 鸽子和野狗 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Jin-Pengyu
      name: GitHub | Jin-Pengyu
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/zhi-nian-20-34-4
      name: zhihu | 希斯特利亚

## [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde #实现markdown中的文字高亮效果
  - pymdownx.arithmatex:
      generic: true # latex支持
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_css:
  #- mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols